/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Connector {
  id?: string;
  standard?:
    | "CHADEMO"
    | "DOMESTIC_A"
    | "DOMESTIC_B"
    | "DOMESTIC_C"
    | "DOMESTIC_D"
    | "DOMESTIC_E"
    | "DOMESTIC_F"
    | "DOMESTIC_G"
    | "DOMESTIC_H"
    | "DOMESTIC_I"
    | "DOMESTIC_J"
    | "DOMESTIC_K"
    | "DOMESTIC_L"
    | "IEC_60309_2_single_16"
    | "IEC_60309_2_three_16"
    | "IEC_60309_2_three_32"
    | "IEC_60309_2_three_64"
    | "IEC_62196_T1"
    | "IEC_62196_T1_COMBO"
    | "IEC_62196_T2"
    | "IEC_62196_T2_COMBO"
    | "IEC_62196_T3A"
    | "IEC_62196_T3C"
    | "TESLA_R"
    | "TESLA_S";
  format?: "SOCKET" | "CABLE";
  power_type?: "AC_1_PHASE" | "AC_3_PHASE" | "DC";
  voltage?: number;
  amperage?: number;
  tariff_id?: string | null;
  terms_and_conditions?: string | null;
  last_updated?: string;
}
