/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Credentials {
  token?: string;
  url?: string;
  business_details?: {
    name: string;
    website?: string | null;
    logo?: null | {
      url: string;
      thumbnail?: string | null;
      category: "CHARGER" | "ENTRANCE" | "LOCATION" | "NETWORK" | "OPERATOR" | "OTHER" | "OWNER";
      type: string;
      width?: number | null;
      height?: number | null;
    };
  };
  party_id?: string;
  country_code?: string;
}
