/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Tariff {
  id: string;
  currency: string;
  tariff_alt_text?:
    | {
        language: string;
        text: string;
      }[]
    | null;
  tariff_alt_url?: string | null;
  elements: [TariffElement, ...TariffElement[]];
  energy_mix?: null | {
    is_green_energy: boolean;
    energy_sources?:
      | {
          source: "NUCLEAR" | "GENERAL_FOSSIL" | "COAL" | "GAS" | "GENERAL_GREEN" | "SOLAR" | "WIND" | "WATER";
          percentage: number;
        }[]
      | null;
    environ_impact?:
      | {
          source: "NUCLEAR_WASTE" | "CARBON_DIOXIDE";
          amount: number;
        }[]
      | null;
    supplier_name?: string | null;
    energy_product_name?: string | null;
  };
  last_updated: string;
}
export interface TariffElement {
  price_components: [
    {
      type: "ENERGY" | "FLAT" | "PARKING_TIME" | "TIME";
      price: number;
      step_size: number;
    },
    ...{
      type: "ENERGY" | "FLAT" | "PARKING_TIME" | "TIME";
      price: number;
      step_size: number;
    }[]
  ];
  restrictions?: {
    start_time?: string | null;
    end_time?: string | null;
    start_date?: string | null;
    end_date?: string | null;
    min_kwh?: number | null;
    max_kwh?: number | null;
    min_power?: number | null;
    max_power?: number | null;
    min_duration?: number | null;
    max_duration?: number | null;
    day_of_week?: ("MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY")[] | null;
  } | null;
}
